const express=require('express');
const pool=require('../config/database');
const {validateTelemetry,validatePlan,validateTransition}=require('../domain/trafficPolicy');
const router=express.Router();
const tenantOf=(req)=>String(req.user.tenant_id||req.user.agency_id||req.user.id);

router.post('/telemetry',async(req,res,next)=>{try{const tenant=tenantOf(req),body=req.body||{};const last=await pool.query('SELECT MAX(source_sequence) AS sequence FROM traffic_telemetry WHERE tenant_id=$1 AND source=$2 AND intersection_id=$3',[tenant,body.source_ref,body.intersection_ref]);const row=validateTelemetry(body,last.rows[0].sequence);await pool.query(`INSERT INTO traffic_telemetry(tenant_id,intersection_id,source,source_sequence,observed_at,values,quality,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[tenant,row.intersection_ref,row.source_ref,row.sequence,row.recorded_at,row.values||{},row.quality||'unverified',{controller_ref:row.controller_ref,schema_version:row.schema_version,checksum:row.checksum,gap:row.gap}]);res.status(202).json({accepted:true,sequence:row.sequence,gap:row.gap});}catch(error){if(error.code==='23505')return res.status(200).json({accepted:true,replayed:true});next(error);}});

router.post('/cases',async(req,res,next)=>{try{if(!req.body.idempotency_key||!req.body.corridor_id||!req.body.constraints||!req.body.objective)throw new Error('idempotency_key, corridor_id, constraints, and objective are required');const tenant=tenantOf(req);const result=await pool.query(`INSERT INTO traffic_optimization_cases(tenant_id,corridor_id,idempotency_key,constraints,objective,created_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[tenant,req.body.corridor_id,req.body.idempotency_key,req.body.constraints,req.body.objective,String(req.user.id)]);res.status(201).json(result.rows[0]);}catch(error){next(error);}});

router.post('/cases/:id/plan',async(req,res,next)=>{try{const tenant=tenantOf(req);const plan=validatePlan(req.body);const result=await pool.query('UPDATE traffic_optimization_cases SET plan=$1,updated_at=NOW() WHERE id=$2 AND tenant_id=$3 RETURNING *',[{...req.body,...plan},req.params.id,tenant]);if(!result.rows[0])return res.status(404).json({error:'Optimization case not found'});res.json(result.rows[0]);}catch(error){next(error);}});

router.post('/cases/:id/transition',async(req,res,next)=>{const client=await pool.connect();try{const tenant=tenantOf(req);await client.query('BEGIN');const found=await client.query('SELECT * FROM traffic_optimization_cases WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,tenant]);const current=found.rows[0];if(!current){await client.query('ROLLBACK');return res.status(404).json({error:'Optimization case not found'});}if(Number(req.body.version)!==current.version){await client.query('ROLLBACK');return res.status(409).json({error:'Stale workflow version'});}validateTransition(current.stage,req.body.to_stage,{...req.body.context,role:req.user.role,actorId:String(req.user.id),createdBy:current.created_by});const result=await client.query('UPDATE traffic_optimization_cases SET stage=$1,version=version+1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.body.to_stage,current.id]);const receipt=req.body.context?.controllerReceipt;if(receipt?.provider&&receipt?.receipt_id)await client.query(`INSERT INTO traffic_integration_deliveries(tenant_id,case_id,provider,operation,idempotency_key,status,receipt) VALUES($1,$2,$3,$4,$5,'acknowledged',$6) ON CONFLICT(tenant_id,provider,idempotency_key) DO NOTHING`,[tenant,current.id,receipt.provider,'signal_plan_dispatch',receipt.receipt_id,receipt]);await client.query('INSERT INTO traffic_workflow_audit(tenant_id,case_id,actor_id,action,from_stage,to_stage,payload) VALUES($1,$2,$3,$4,$5,$6,$7)',[tenant,current.id,String(req.user.id),'traffic.transitioned',current.stage,req.body.to_stage,req.body.context||{}]);await client.query('COMMIT');res.json(result.rows[0]);}catch(error){await client.query('ROLLBACK').catch(()=>{});next(error);}finally{client.release();}});
module.exports=router;
